import { navigationResources } from './resources.mjs';
import { routeIcon, collectionMap } from './visuals.mjs';
export const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export const base = '/awesome-proactive-agent/';
export const repo = 'https://github.com/LowEntropyAI/awesome-proactive-agent';
export const url = path => base + path;
export const bi = (en, zh, tag = 'span') => `<${tag} data-en="${esc(en)}" data-zh="${esc(zh)}">${esc(en)}</${tag}>`;
export const arrow = '<span aria-hidden="true">↗</span>';
export const eyebrow = (en, zh) => `<div class="eyebrow">${bi(en, zh)}</div>`;
export const heading = (en, zh, subEn = '', subZh = '') => `<div class="page-heading">${bi(en, zh, 'h1')}${subEn ? bi(subEn, subZh, 'p') : ''}</div>`;
const brand = `<a class="brand" href="${base}"><span class="brand-icon"><img src="${url('assets/lowentropyai.png')}" width="28" height="28" alt="" aria-hidden="true"></span><strong>LowEntropy<span>AI</span></strong><span class="brand-divider">/</span><span class="brand-project"><strong class="brand-proactive">Proactive</strong> agents</span></a>`;
export function layout(title, content, path, stats = {}, description = 'A directory of proactive AI research. Explore agents, models, projects, and benchmarks.', extra = '') {
  const nav = [['applications/', 'Applications', '应用'], ['library/', 'Papers', '论文'], ['projects/', 'Projects', '项目'], ['benchmarks/', 'Benchmarks', '基准']];
  return `<!doctype html><html lang="en" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} · LowEntropyAI</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://lowentropyai.github.io${url(path)}"><meta property="og:title" content="${esc(title)} · LowEntropyAI"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:url" content="https://lowentropyai.github.io${url(path)}"><meta property="og:image" content="https://lowentropyai.github.io${url('assets/social.svg')}"><meta name="theme-color" content="#f7f8fa"><link rel="icon" href="${url('assets/lowentropyai.png')}" type="image/png"><link rel="stylesheet" href="${url('assets/style.css')}">${extra}<script src="${url('assets/theme.js')}"></script><script type="module" src="${url('assets/app.js')}"></script></head><body data-base="${base}" data-page="${path}"><a class="skip" href="#main">Skip to content</a><header class="site-header"><div class="header-inner">${brand}<nav aria-label="Main navigation">${nav.map(([p, en, zh]) => `<a href="${url(p)}" ${path.startsWith(p) ? 'aria-current="page"' : ''}>${bi(en, zh)}</a>`).join('')}<a class="nav-utility github-link" href="${repo}">GitHub ${arrow}</a><a class="nav-utility add-paper-link" href="${repo}/blob/main/CONTRIBUTING.md">${bi('Add a paper', '添加论文')} ${arrow}</a></nav><div class="header-actions"><button id="language" aria-label="Switch language">中文</button><button id="theme" aria-label="Switch color theme">◐</button></div></div></header><main id="main">${content}</main><footer><div><span>LowEntropyAI</span><span class="footer-separator">/</span>${bi('Awesome Proactive Agent', '主动式智能体资源库')}</div></footer></body></html>`;
}
export function resourceLinks(p) {
  return navigationResources(p).map(r => {
    const label = r.label;
    return `<a class="resource-link${label === 'Repo' ? ' repo-link' : ''}" href="${esc(r.url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ${arrow}</a>`;
  }).join('');
}
function paperTags(p) {
  return `<div class="tags">${(p.tags || []).map(t => `<a href="${url('library/')}?tag=${encodeURIComponent(t)}">${esc(t)}</a>`).join('')}</div>`;
}
export function paperCard(p, { compact = false } = {}) {
  return `<article class="paper-card${compact ? ' compact' : ''}"><div class="paper-main"><div class="paper-meta"><span>${esc(p.date)}</span><span>${esc(p.venue)}</span></div><h3><a href="${esc(p.primary || p.resources?.[0]?.url || repo)}" target="_blank" rel="noopener noreferrer">${esc(p.title)} ${arrow}</a></h3>${paperTags(p)}</div><div class="resource-links">${resourceLinks(p)}</div></article>`;
}
export function selectedCard(p) {
  const thumbnail = p.thumbnail;
  const src = thumbnail?.src?.startsWith('http') || thumbnail?.src?.startsWith('/') ? thumbnail.src : url(thumbnail?.src || '');
  return `<article class="selected-card">${thumbnail ? `<a class="selected-image" href="${esc(thumbnail.original || thumbnail.source || p.primary)}" target="_blank" rel="noopener noreferrer"><img src="${esc(src)}" alt="${esc(thumbnail.alt || `${p.title} overview`)}" loading="lazy"><span class="figure-link">${bi('Overview', '概览图')} ${arrow}</span></a>` : ''}<div class="selected-body">${thumbnail?.source ? `<a class="image-credit" href="${esc(thumbnail.source)}" target="_blank" rel="noopener noreferrer">${esc(thumbnail.caption || 'Original figure source')} ${arrow}</a>` : ''}<div class="paper-meta"><span>${esc(p.date)}</span><span>${esc(p.venue)}</span></div><h3><a href="${esc(p.primary)}" target="_blank" rel="noopener noreferrer">${esc(p.displayTitle || p.title)}</a></h3>${p.description ? `<p class="selected-description">${esc(p.description)}</p>` : ''}${paperTags(p)}<div class="resource-links">${resourceLinks(p)}</div></div></article>`;
}
function directoryNav(catalog, active = '') {
  const item = (path, en, zh, icon, key = '', count = null) => `<a href="${url(path)}"${key && active === key ? ' class="current" aria-current="page"' : ''}><span class="nav-item-label"><span class="sidebar-icon">${routeIcon(icon)}</span>${bi(en, zh)}</span>${count === null ? '' : `<span class="count">${count}</span>`}</a>`;
  const browse = [
    ['start/', 'Must Read', '分层必读', 'book', 'start'],
    ['personal/', 'Personal agents', '个人智能体', 'agent', 'personal'],
    ['infrastructure/', 'Supporting infrastructure', '基础设施', 'layers', 'infrastructure'],
    ['map/', 'Research map', '研究地图', 'grid', 'map']
  ];
  const icons = { foundations: 'book', interaction: 'interaction', 'computer-use': 'monitor', multimodal: 'vision', evaluation: 'benchmark' };
  return `<aside class="directory-sidebar" aria-label="Resource navigation"><div class="sidebar-group"><span class="sidebar-label">${bi('Browse', '浏览')}</span>${browse.map(row => item(...row)).join('')}</div><div class="sidebar-group"><span class="sidebar-label">${bi('Research areas', '研究方向')}</span>${catalog.categories.map(c => item(`library/?category=${c.key}`, c.short, c.zh, icons[c.key], '', catalog.papers.filter(p => p.categories.includes(c.key)).length)).join('')}</div></aside>`;
}
function searchBox({ home = false } = {}) {
  return `<form id="${home ? 'home-search' : 'search-form'}" class="search-form" role="search" ${home ? `action="${url('library/')}" method="get"` : ''}><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" stroke-width="1.7"/><path d="m16 16 4 4" stroke="currentColor" stroke-width="1.7"/></svg><input id="search" name="q" type="search" aria-label="Search papers and resources" placeholder="Search papers, models, topics…" data-placeholder-en="Search papers, models, topics…" data-placeholder-zh="搜索论文、模型、研究主题…"><kbd>/</kbd><button type="submit">${bi('Search', '搜索')} <span aria-hidden="true">→</span></button></form>`;
}
export function home(catalog) {
  const picks = catalog.papers.filter(p => p.selected).sort((a, b) => a.selectedOrder - b.selectedOrder);
  const groups = [['agent', 'Proactive Agents', '主动式智能体'], ['model', 'Models', '模型'], ['benchmark', 'Benchmarks', '评测基准']];
  const selectionRows = 1 + Math.max(...groups.map(([key]) => picks.filter(p => p.selectionGroup === key).length));
  const selected = `<div class="selected-route-grid" style="--selection-rows:${selectionRows}">${groups.map(([key, en, zh]) => `<section class="selected-route" data-selection-group="${key}"><h3 class="selected-route-title"><span class="route-symbol">${routeIcon(key)}</span>${bi(en, zh)}</h3><div class="selected-group-cards">${picks.filter(p => p.selectionGroup === key).map(selectedCard).join('')}</div></section>`).join('')}</div>`;
  return `<div class="directory-layout">${directoryNav(catalog)}<div class="directory-content"><div class="directory-heading"><div>${eyebrow('RESEARCH DIRECTORY', '研究资源导航')}<div class="page-heading proactive-heading"><span class="awesome-kicker">Awesome</span><h1><span class="proactive-emphasis">${bi('Proactive', '主动式')}</span> ${bi('Agents', '智能体')}</h1>${bi('Proactive AI across personal assistance, streaming interaction, and embodied environments.', '面向个人助手、流式交互与具身环境的主动式 AI。', 'p')}</div></div></div>${searchBox({ home: true })}<div class="quick-topics"><span>${bi('Explore', '快速浏览')}</span>${['Streaming', 'Memory', 'Personalization', 'GUI'].map(t => `<a href="${url('library/')}?tag=${encodeURIComponent(t)}">${t} ${arrow}</a>`).join('')}</div><section class="directory-section"><div class="section-heading"><h2>${bi('Selected', '精选工作')}<span class="section-index">01</span></h2><a href="${url('library/')}?featured=1">${bi('Browse selected papers', '查看精选论文')} →</a></div>${selected}</section>${collectionMap(url, bi)}<section class="directory-section recent-section"><div class="section-heading"><h2>${bi('Recent papers', '近期论文')}<span class="section-index">02</span></h2><a href="${url('library/')}">${bi('All papers', '全部论文')} →</a></div><div class="paper-grid">${catalog.papers.slice(0, 8).map(p => paperCard(p)).join('')}</div></section></div></div>`;
}
export function library(catalog, streaming = false) {
  const list = streaming ? catalog.papers.filter(p => p.streaming) : catalog.papers;
  return `<div class="directory-layout library-directory">${directoryNav(catalog, streaming ? 'streaming' : 'all')}<div class="directory-content">${heading(streaming ? 'Streaming models' : 'Paper directory', streaming ? '流式模型' : '论文导航', streaming ? 'Continuous video, audio, memory, and real-time interaction.' : 'Find original papers, repositories, and project pages.', streaming ? '连续视频、音频、记忆与实时交互。' : '查找原始论文、代码仓库与项目主页。')}<div id="catalog" data-streaming="${streaming}">${searchBox()}<div class="filter-bar"><div class="filter-selects"><label class="sr-only" for="category">Research area</label><select id="category"><option value="" data-en="All areas" data-zh="全部方向">All areas</option>${catalog.categories.map(c => `<option value="${c.key}" data-en="${esc(c.short)}" data-zh="${esc(c.zh)}">${esc(c.short)}</option>`).join('')}</select><label class="sr-only" for="tag">Topic</label><select id="tag"><option value="" data-en="All topics" data-zh="全部主题">All topics</option>${[...new Set(list.flatMap(p => p.tags))].sort().map(t => `<option>${esc(t)}</option>`).join('')}</select><label class="sr-only" for="year">Year</label><select id="year"><option value="" data-en="Year" data-zh="年份">Year</option>${[...new Set(list.map(p => p.date.slice(0, 4)))].sort().reverse().map(y => `<option>${y}</option>`).join('')}</select><label class="sr-only" for="venue">Venue</label><select id="venue"><option value="" data-en="Venue" data-zh="发表来源">Venue</option>${[...new Set(list.map(p => p.venue.startsWith('arXiv') ? 'arXiv' : p.venue))].sort().map(v => `<option>${esc(v)}</option>`).join('')}</select></div><div class="filter-checks"><label class="check"><input type="checkbox" id="code">${bi('With code', '含代码')}</label><label class="check"><input type="checkbox" id="featured">${bi('Selected', '精选')}</label><button id="clear-filters">${bi('Reset', '重置')}</button></div></div><div class="results-toolbar"><span id="result-count" role="status" aria-live="polite">${list.length} ${bi('papers', '篇论文')}</span><label for="sort" class="sr-only">Sort papers</label><select id="sort"><option value="newest" data-en="Newest first" data-zh="最新优先">Newest first</option><option value="oldest" data-en="Oldest first" data-zh="最早优先">Oldest first</option><option value="title" data-en="Title A–Z" data-zh="标题 A–Z">Title A–Z</option><option value="relevance" data-en="Relevance" data-zh="相关性">Relevance</option></select></div><div id="active-filters" class="active-filters"></div><div id="paper-results" class="paper-grid">${list.slice(0, 20).map(p => paperCard(p)).join('')}</div><div id="pagination" class="pagination"></div><noscript><p>Enable JavaScript for search and filtering.</p><ul>${list.map(p => `<li><a href="${esc(p.primary)}">${esc(p.title)}</a></li>`).join('')}</ul></noscript></div></div></div>`;
}
function simpleDirectorySearch(count, en, zh) {
  return `<div class="search-form"><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5" stroke="currentColor" stroke-width="1.7"/><path d="m16 16 4 4" stroke="currentColor" stroke-width="1.7"/></svg><input id="directory-search" type="search" aria-label="Search resources" placeholder="Search resources…" data-placeholder-en="Search resources…" data-placeholder-zh="搜索资源…"><kbd>/</kbd></div><div class="results-toolbar"><span id="directory-count" role="status" aria-live="polite" data-noun-en="${en}" data-noun-zh="${zh}">${count} ${bi(en, zh)}</span></div>`;
}
export function projectPage(catalog) {
  const projects = catalog.projects || [];
  return `<div class="directory-layout">${directoryNav(catalog, 'projects')}<div class="directory-content">${heading('Projects & code', '项目与代码', 'Open repositories, working implementations, and project pages.', '开源仓库、项目实现与官方主页。')}${simpleDirectorySearch(projects.length, 'projects', '个项目')}<div id="directory-results" class="projects-grid">${projects.map(p => `<article class="project-card" data-search="${esc([p.title, p.name, p.description, p.groupLabel, p.groupZh, ...(p.resources || []).map(r => r.url)].filter(Boolean).join(' '))}"><h2><a href="${esc(p.primary || p.url || p.resources?.[0]?.url || repo)}" target="_blank" rel="noopener noreferrer">${esc(p.title || p.name)} ${arrow}</a></h2>${p.description ? `<p>${esc(p.description)}</p>` : ''}<div class="tags"><span>${bi(p.groupLabel || p.category || p.kind || 'Project', p.groupZh || p.groupLabel || '项目')}</span></div><div class="resource-links">${resourceLinks(p)}</div></article>`).join('')}</div></div></div>`;
}
export function benchmarkPage(catalog) {
  const benchmarks = catalog.benchmarks || [];
  return `<div class="directory-layout">${directoryNav(catalog, 'benchmarks')}<div class="directory-content">${heading('Benchmarks', '评测基准', 'Datasets and evaluation suites for proactive agents.', '主动式智能体的数据集与评测套件。')}${simpleDirectorySearch(benchmarks.length, 'benchmarks', '个基准')}<div id="directory-results" class="paper-grid">${benchmarks.map(b => `<article class="paper-card" data-search="${esc([b.name, b.paper, b.domain, b.target, ...(b.resources || []).map(r => r.url)].filter(Boolean).join(' '))}"><div class="paper-main"><div class="paper-meta">${b.date ? `<span>${esc(b.date)}</span>` : ''}</div><h3><a href="${esc(b.primary || b.resources?.[0]?.url || repo)}" target="_blank" rel="noopener noreferrer">${esc(b.name)} ${arrow}</a></h3>${b.paper && b.paper !== b.name ? `<div class="benchmark-paper">${esc(b.paper)}</div>` : ''}<div class="tags"><span>${esc(b.domain)}</span></div></div><div class="resource-links">${resourceLinks(b)}</div></article>`).join('')}</div></div></div>`;
}

export function guidePage(catalog, html, active = '') {
  return `<div class="directory-layout">${directoryNav(catalog, active)}<article class="directory-content prose">${html}</article></div>`;
}
